language: php
php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - nightly
install:
    - sudo apt-get update
    - sudo apt-get install -y valgrind
matrix:
  allow_failures:
    - php: nightly
script:
    - phpize
    - ./configure
    - make
    - REPORT_EXIT_STATUS=1 TEST_PHP_ARGS="-q --show-diff" make test
