language: php
php:
    - 5.4
    - 5.5
    - 5.6
before_script: phpenv config-rm xdebug.ini
script:
    - phpize
    - ./configure
    - make
    - REPORT_EXIT_STATUS=1 TEST_PHP_ARGS="-q --show-diff" make test
