language: php
php:
    - 7.0
    - nightly
install:
    - sudo apt-get update
    - sudo apt-get install -y valgrind
script:
    - phpize
    - ./configure
    - make
    - REPORT_EXIT_STATUS=1 TEST_PHP_ARGS="-m -q --show-diff" make test
